version: '3'

services:
  dockerc:
    build: 
      context: dockerc
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ../..:/workspaces:cached
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    cap_add:
     - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  api:
    image: "hashicorpdemoapp/product-api:v0.0.22"
    ports:
      - "19090:9090"
    volumes:
      - ./conf.json:/config/config.json
    environment:
      CONFIG_FILE: '/config/config.json'
    depends_on:
      - db
  db:
    image: "hashicorpdemoapp/product-api-db:v0.0.22"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: 'products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'